### PR TITLE
fix(kaktwoos): nvidia-name inconsistency and start-end print fixes

### PR DESCRIPTION
**Pull request by Hyenadae**
Nvidia has decided that some gpus are named "GeForce GTX" while others are "NVIDIA GeForce RTX/GTX", meaning the Nvidia optimization toggle won't always catch the device name properly.

This should hopefully mean it always begins the char-compare for the character after the space in GEFORCE

Also, AMD cards will now print their GPU name, which is "GFX900" on Vega for example.

### CODE REVIEW

**Comment by Hyenadae** [comment]
For conflict resolution, please keep the "tmpBuffer=buffer+8" set of changes. Don't know why git isn't overwriting it, but whatever the mchome repo has is wrong. 

Vega 56 test run
Received work unit: 9567961692053
Data: n1: 856, n2: 344, n3: 840, di: 0, ch: 12, f: 63, s: 4500000000, e: 6000000000
15:09:38 (3400): Can't open init data file - running in standalone mode
Error: boinc_get_opencl_ids() failed with error -108
DEVICE_NAME = gfx900
No checkpoint to load
    Found seed: 5861434992872476197, 77849775653, height: 20
5861434992872476197
Speed: 53.46m/s 
Done
Processed 1500000000 seeds in 28.088000 seconds
Found seeds: 
    5861434992872476197

GTX 1650M run
Received work unit: 9567961692053
Data: n1: 856, n2: 344, n3: 840, di: 0, ch: 12, f: 63, s: 4500000000, e: 6000000000
14:54:33 (736): Can't open init data file - running in standalone mode
Error: boinc_get_opencl_ids() failed with error -108
DEVICE_NAME = GeForce GTX 1650
GTX 16XX, Optimizations applied!
No checkpoint to load
  Found seed: 5861434992872476197, 77849775653, height: 20
5861434992872476197
Speed: 43.84m/s 
Done
Processed 1500000000 seeds in 34.225000 seconds
Found seeds: 
    5861434992872476197

**Comment by Hyenadae** [comment]
Also yeah it seems intel GPU - linux works fine still, so we're good. Just gotta remember to make sure BOINC doesn't ever complain about filesize differences again. There shouldn't be any reason now either

**Review by BoySanic — APPROVED** [review]
Looks good to me. I think we included all the changes we had discussed the last time we looped around to optimization switching.

:shipit:

**Comment by Hyenadae** [comment]
Ignore this also, merged a week ago!

**Pull request closed without merging**
